version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    hostname: rabbitmq-node1
    ports:
      # AMQP protocol port
      - 5672:5672
      # HTTP management UI
      - 15672:15672